"""Pydantic models for the wargame engine.

Core data contracts: scenario configuration, game state, turn execution packets.
All IDs are system-assigned (engine-generated), never LLM-generated.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Scenario configuration (loaded from YAML, immutable during game)
# ---------------------------------------------------------------------------

class ActorValue(BaseModel):
    """Terminal evaluative commitment for an actor."""
    id: str
    name: str
    weight: float = Field(ge=0.0, le=1.0)


class ClassificationRule(BaseModel):
    """How an actor categorizes a phenomenon (e.g., sanctions = coercion)."""
    subject: str
    category: str


class CharacterModel(BaseModel):
    """Behavioral parameters for AI-played actors. Sampled in probabilistic mode."""
    risk_posture: float = Field(0.5, ge=0.0, le=1.0, description="0=averse, 1=acceptant")
    ideological_weight: float = Field(0.5, ge=0.0, le=1.0, description="0=pragmatic, 1=doctrinaire")
    escalation_threshold: float = Field(0.5, ge=0.0, le=1.0, description="0=low (escalates easily), 1=high (restraint)")
    cooperation_openness: float = Field(0.5, ge=0.0, le=1.0, description="0=closed, 1=open to deals")


class Instrument(BaseModel):
    """A tool/channel available to an actor, tagged with MIDFIELD domains."""
    id: str
    midfield: list[str]
    target_vars: list[str]


class ActorSpec(BaseModel):
    """Full specification of an actor in a scenario."""
    id: str
    name: str
    type: str
    values: list[ActorValue]
    classification_rules: list[ClassificationRule] = Field(default_factory=list)
    character: CharacterModel = Field(default_factory=CharacterModel)
    instruments: list[Instrument]


class DomainModel(BaseModel):
    """How a geopolitical domain works — used by GM for adjudication."""
    id: str
    subtype: str
    description: str
    key_variables: list[str] = Field(default_factory=list)
    base_rates: dict[str, float] = Field(default_factory=dict)


class StateVariableSpec(BaseModel):
    """Specification for a state variable in the scenario."""
    id: str
    type: Literal["structural", "positional", "flow", "institutional", "perceptual"]
    domain: str
    timescale: Literal["slow", "medium", "fast"]
    range: list[float] = Field(min_length=2, max_length=2)
    unit: str = ""
    holder: str = ""  # For perceptual vars: which actor holds this perception


class CausalEdge(BaseModel):
    """Directed causal relationship between state variables."""
    source: str
    target: str
    effect: float  # multiplier: target_delta = effect * source_delta
    lag: int = 0  # turns before effect applies
    actor: str = ""  # empty = global; actor_id = perceptual scope


class VariableDynamic(BaseModel):
    """Per-variable decay or momentum."""
    decay_rate: float | None = None  # per-turn decay (toward baseline)
    momentum: float | None = None  # per-turn autonomous change


class MultiTurnActionTemplate(BaseModel):
    """Template for actions that take multiple turns to complete."""
    duration: int | Literal["ongoing"] = 1
    resource_cost_per_turn: int
    domain: str
    target_var: str
    effect_per_turn: list[float]
    interruptible: bool = True


class ResourceBudgetSpec(BaseModel):
    """Per-actor resource allocation."""
    per_turn: int
    domains: dict[str, int]


class ScenarioMeta(BaseModel):
    """Top-level scenario metadata."""
    name: str
    turns: int
    time_per_turn: str
    description: str = ""


class ScenarioSpec(BaseModel):
    """Complete scenario specification loaded from YAML."""
    meta: ScenarioMeta
    actors: list[ActorSpec]
    domain_models: list[DomainModel] = Field(default_factory=list)
    state_variables: list[StateVariableSpec]
    causal_edges: list[CausalEdge] = Field(default_factory=list)
    variable_dynamics: dict[str, VariableDynamic] = Field(default_factory=dict)
    multi_turn_actions: dict[str, MultiTurnActionTemplate] = Field(default_factory=dict)
    initial_state: dict[str, float]
    resource_budget: dict[str, ResourceBudgetSpec]


# ---------------------------------------------------------------------------
# Turn execution packets
# ---------------------------------------------------------------------------

class ActionIntent(BaseModel):
    """Structured parse of a player directive. Generated by Parser LLM.

    action_id is assigned by the engine post-parse, not by the LLM.
    """
    actor_id: str = Field(description="ID of the acting player/agent")
    action_category: Literal["kinetic", "diplomatic", "covert", "economic", "information", "resource_allocation"]
    target_entities: list[str] = Field(description="IDs of targeted actors, regions, or assets")
    instruments_used: list[str] = Field(description="Canonical instrument IDs from the scenario spec")
    intended_effect: str = Field(description="1-2 sentence summary of desired outcome")
    resource_cost: int = Field(description="Estimated resource points this action consumes", ge=1)
    ambiguity_flags: list[str] = Field(default_factory=list)


class StateTransition(BaseModel):
    """A single variable change."""
    var_id: str = Field(description="Must match a var_id from the scenario spec")
    delta: float = Field(description="Change to apply. Positive = increase.")


class OutcomeBranch(BaseModel):
    """One possible outcome of an action with its probability."""
    outcome_id: Literal["critical_success", "success", "partial", "failure", "critical_failure"]
    narrative: str = Field(description="2-3 sentence description of what happens")
    probability: float = Field(ge=0.0, le=1.0)
    state_transitions: list[StateTransition]


class PerActorObservation(BaseModel):
    """What a specific actor sees, keyed by outcome_id."""
    actor_id: str
    observations: dict[str, list[str]] = Field(
        description="Keyed by outcome_id. Value is list of observation strings."
    )


class AdjudicationPacket(BaseModel):
    """GM's assessment of an action. Probabilities must sum to 1.0."""
    reasoning: str = Field(description="GM's chain-of-thought explaining the assessment")
    possible_outcomes: list[OutcomeBranch]
    observability: list[PerActorObservation]

    @model_validator(mode="after")
    def check_probabilities_sum(self) -> "AdjudicationPacket":
        """Validate that outcome probabilities sum to ~1.0."""
        total = sum(o.probability for o in self.possible_outcomes)
        if abs(total - 1.0) > 0.05:
            raise ValueError(f"Probabilities sum to {total:.4f}, must be within 0.05 of 1.0")
        return self


class ObservationPacket(BaseModel):
    """What a specific actor learns after a turn resolves."""
    turn_number: int
    actor_id: str
    observations: list[str] = Field(description="Narrative observations this actor receives")
    state_estimate_updates: dict[str, float] = Field(
        default_factory=dict,
        description="Updated estimates for observable variables. NOT canonical values.",
    )
